### ISSUE TITLE
weathermap crash cannot enable anymore

### ISSUE THREAD

**Issue by dallenk** [thurban/plugin_weathermap#167]
I disabled weathermap a while ago while troubleshooting some poller overruns and just tried to re-enable.  fresh reset --hard to current and reconfigured with new path location for configs and output.

crash on first attempt to create a map.

```
2024-12-24 15:27:17 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2024-12-24 15:27:17 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-24 15:27:17 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught Error: Found unconstructed IntlDateFormatter in /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php:1947 Stack trace: #0 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(1947): IntlDateFormatter->format() #1 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2043): WeatherMap->{closure}() #2 [internal function]: WeatherMap->{closure}() #3 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2045): preg_replace_callback() #4 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2053): WeatherMap->strftime() #5 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(3646): WeatherMap->DrawTimestamp() #6 /var/www/html/cacti/plugins/weathermap/lib/poller-common.php(461): WeatherMap->DrawMap() #7 /var/www/html/cacti/plugins/weathermap/setup.php(1233): weathermap_run_maps() #8 /var/www/html/cacti/lib/plugins.php(243): weathermap_poller_bottom() #9 /var/www/html/cacti/lib/plugins.php(97): api_plugin_run_plugin_hook() #10 /var/www/html/cacti/poller.php(991): api_plugin_hook() #11 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 1947
2024-12-24 15:27:16 - POLLER: Poller[Main Poller] PID[261075] ERROR: Process being killed due to timeout! (weathermap, master, 0, Process 4073243, Time 1735077375, Timeout 300, Timestamp 1735082836)
```

intl is installed:
php-intl is already the newest version (2:8.3+95+ubuntu22.04.1+deb.sury.org+1).

that is about the extent of my php troubleshooting knowledge unfortunatly.

This can wait until after xmas  and new years!   Have a great holiday!

**Comment by TheWitness** [comment]
Don't use the development tag it's under heavy work and quite broken right now use the previous tag.

**Comment by dallenk** [comment]
that works.  sorry i should have tried that first.

**Comment by TheWitness** [comment]
Glad you worked it out.  I'll get it fixed in the new year.

**Comment by dallenk** [comment]
that was short lived lol.  errors came back.  I also downloaded the zip for 1.3 instead of using git for it (honestly I coudn't figure out how to remove the develop tag from it.. tried checkout / git tag ect..)

anywho
```
2025-01-02 14:48:12 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2025-01-02 14:48:12 - PHP ERROR Backtrace: (CactiShutdownHandler())
2025-01-02 14:48:12 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught Error: Found unconstructed IntlDateFormatter in /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php:1930 Stack trace: #0 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(1930): IntlDateFormatter->format() #1 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2026): WeatherMap->{closure}() #2 [internal function]: WeatherMap->{closure}() #3 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2028): preg_replace_callback() #4 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(2036): WeatherMap->strftime() #5 /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php(3627): WeatherMap->DrawTimestamp() #6 /var/www/html/cacti/plugins/weathermap/lib/poller-common.php(442): WeatherMap->DrawMap() #7 /var/www/html/cacti/plugins/weathermap/setup.php(1169): weathermap_run_maps() #8 /var/www/html/cacti/lib/plugins.php(243): weathermap_poller_bottom() #9 /var/www/html/cacti/lib/plugins.php(97): api_plugin_run_plugin_hook() #10 /var/www/html/cacti/poller.php(1003): api_plugin_hook() #11 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/lib/WeatherMap.class.php on line: 1930
```

`Weathermap	Weathermap Plugin	Disabled by Error	Howard Jones and The Cacti Group	>= 1.2.24		1.3	2025-01-02 14:48	`

php-intl is installed, promise!  lol
```
php8.1-intl/jammy,now 8.1.31-1+ubuntu22.04.1+deb.sury.org+1 amd64 [installed]
php-intl/jammy,now 2:8.3+95+ubuntu22.04.1+deb.sury.org+1 all [installed]
```

hrm.. just notice this one in the log also:
2025-01-02 23:07:05 - CMDPHP The table with the Table ID weathermap-cacti-plugin-mgmt:action-addmap_picker: is not using form_selectable_cell() correctly


oh.. and I just noticed this for the first time:
```
2025-01-02 15:13:03 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'weathermap'
2025-01-02 15:13:03 - PHP ERROR Backtrace: (CactiShutdownHandler())
2025-01-02 15:13:03 - ERROR PHP ERROR in Plugin 'weathermap': Uncaught Error: Call to undefined function plugin_weathermap_numeric_version() in /var/www/html/cacti/plugins/weathermap/weathermap-cacti-plugin.php:713 Stack trace: #0 /var/www/html/cacti/plugins/weathermap/weathermap-cacti-plugin.php(350): weathermap_versionbox() #1 {main} thrown in file: /var/www/html/cacti/plugins/weathermap/weathermap-cacti-plugin.php on line: 713
```

i did find a reference to the function in setup.php.. perhaps missing:  include_once('./setup.php');  ?
