### ISSUE TITLE
Map Properties-Map Size-Unable to display the entire map.

### ISSUE THREAD

**Issue by jackfish0405** [thurban/plugin_weathermap#64]
When the Map Properties setting Map Size is very large,
1>On the page to edit the map，there is no scroll bar on the right and bottom of the page to drag.
2>On the page browsing the map, there is no bottom scroll bar to drag, and the full width of the map cannot be displayed.
For example: Map Size 4000*2000.

**Comment by TheWitness** [comment]
Is this a feature request or a bug.  I've not used wm before.  So, the question may sound odd.

**Comment by arno-st** [comment]
I have the same issue, even if on my side a have the vertical scroll, but not the horizontal one.
So I'd like to say it's a bug !

**Comment by jackfish0405** [comment]
I think it should be regarded as a bug. There are also requests for such high-pixel maps.
Draw high pixels, use a lower resolution display, and cannot browse the entire map without scroll bars.

There is no horizontal and vertical scroll bar to drag the page on the edit map page.
![image](https://user-images.githubusercontent.com/53333879/214568892-2276443b-43ee-477c-b500-db75623efcec.png)

Previous versions did not have this problem.
![image](https://user-images.githubusercontent.com/53333879/214569092-69760f8a-9f06-4ce0-84f1-174837fc4ae8.png)
![image](https://user-images.githubusercontent.com/53333879/214569274-3dbab4cd-52ab-4601-b921-26c05e92ba88.png)

There is no horizontal scroll bar at the bottom of the map display page.
![image](https://user-images.githubusercontent.com/53333879/214571678-a0d53180-7b22-4b81-8965-9c64af1977cd.png)

**Comment by jackfish0405** [comment]
In addition, when using high pixels, such as 4000*2000。you cannot add node in the box area. I think it is necessary to draw a larger map in many cases.
![image](https://user-images.githubusercontent.com/53333879/214573234-438af961-bb17-4c37-9dbd-8ca9b70d9580.png)
![image](https://user-images.githubusercontent.com/53333879/214573995-2659b1e2-96cf-433d-be0c-70e5c0f43caf.png)

**Comment by TheWitness** [comment]
Let me check this one out.  Should be simple CSS.  Have to override Cacti CSS.

**Comment by TheWitness** [comment]
Okay, this is fixed in my personal repo until Beta-3 is out or the release.

**Comment by arno-st** [comment]
Sorry not close yet, this issue it still present when you edit a map.
For the display on the Weathermap tab it's doing great.

**Comment by TheWitness** [comment]
You will have to be much more specific.

**Comment by arno-st** [comment]
Sorry, There was 2 points on the start of this thread.
The point 1 is not resolve:
`When the Map Properties setting Map Size is very large,
1>On the page to edit the map，there is no scroll bar on the right and bottom of the page to drag.
`
You solve the point 2 on the weathermap tab page, now we have scroll bar on the side and on the bottom, but not on the console-> weathermap->'edition of a large map'

**Comment by TheWitness** [comment]
In the previously WeatherMap releases was there a scroll bar, or did the image just get resized to the page size?  And how did you know the other point since you did not have a scroll bar before?  Seems almost like a new issue.  Well it is a new issue.  So, can you please open a new case?

**Comment by arno-st** [comment]
Well in version 0.98a I have an vertical scroll bar
But the image was resize on the horizontal size.

As for the other point (point 2) I know it's solve since now I have both scroll bar. any way i can open a new case no problem.

**Comment by jackfish0405** [comment]
I opened another case describing the issue at #74.

**Comment by TheWitness** [comment]
Cool thanks.  The scroll is still there, but for some reason, the horizontal scroll bar on the editor is missing.  You can use the scroll wheel on the mouse combined with the shift key to still scroll.  Have to figure out why the scrollbar is not visible though.

**Comment by TheWitness** [comment]
I'll comment further in the new ticket.
